## NUMPY 

What is NumPy?
NumPy, short for Numerical Python, is one of the most important foundational packages for numerical computing in Python. It is specifically designed for efficiency on large arrays of data. NumPy stores data in contiguous blocks of memory and uses C-based algorithms to perform complex computations on entire arrays—completely bypassing the need for slow Python for loops

1. The ndarray Object   
The core feature of NumPy is its N-dimensional array object, or ndarray. It is a fast, flexible container for large datasets that allows you to perform batch mathematical operations using the same syntax you would use for single scalar values. 
 Every array has two important attributes:  
 shape: A tuple indicating the size of each dimension.
 dtype: An object describing the data type of the array (e.g., float64, int32).

2. Creating Arrays
The easiest way to create an array is to use the np.array function, which accepts any sequence-like object (like a list) and converts it into a NumPy array.  

# Lecture 1: NumPy Basics, Creating Arrays, Arithmetic, and Data Types

In [1]:
import numpy as np 

# Creating a 1-dimensional array from a list
data1 = [6,2.7,5,8,8.8]
arr1 = np.array(data1)

# Creating a 2-dimensional array from a list of lists
data2 = [[2.7 ,3,9] , 
         [6,7,8]
         ]
arr2 = np.array(data2)
type(arr2)

# Creating a 2-dimensional  unequal element array  from a list of lists
arr3 = np.array([[3,4] , [4,5,6] ], dtype = object)
type(arr3)
print(arr3)
print(arr2)



[list([3, 4]) list([4, 5, 6])]
[[2.7 3.  9. ]
 [6.  7.  8. ]]


NumPy also provides built-in functions to generate arrays from scratch:  

In [2]:
np.zeros(10)   # Creates an array of 10 zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones((3,6))   # Creates a 3x6 multidimensional array of 1s
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [4]:
np.arange(5,15)  #  Works just like Python's built-in range() function, but returns an array instead of a list.

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

3. Array Arithmetic (Vectorization)
One of the most powerful features of arrays is that they enable you to perform operations on entire datasets without writing loops. NumPy users call this vectorization.  
Any arithmetic operations between equal-size arrays apply the operation element-by-element:  

In [5]:
arr  = np.array([[2,3,4] , 
                 [5,6,7]])

# Multiplication multiplies corresponding elements
print(arr*arr)

# Arithmetic with scalars propagates the value to each element
arr* 10 

[[ 4  9 16]
 [25 36 49]]


array([[20, 30, 40],
       [50, 60, 70]])

4. Data Types and Casting
You can explicitly convert (or cast) an array from one data type to another using the astype method.

In [6]:
arr = np.array([1, 2, 3, 4, 5]) # This is an integer array
float_arr = arr.astype(np.float64) # Now it is a float array

 ## Lecture 2: Indexing and Slicing (Learning how to select specific data, including basic slicing, boolean indexing, and "fancy" indexing).

Lecture 3: Transposing Arrays and Universal Functions (Swapping axes and applying fast, element-wise array functions like square roots or exponentials).

Lecture 4: Array-Oriented Programming (Expressing conditional logic as array operations, mathematical/statistical methods, and sorting).

Lecture 5: File Input/Output and Linear Algebra (Saving/loading arrays to disk and basic matrix operations like dot products).

Lecture 6: Pseudorandom Number Generation & A Practical Example (Generating random data and building a "Random Walk" simulation).