## NUMPY 

What is NumPy?
NumPy, short for Numerical Python, is one of the most important foundational packages for numerical computing in Python. It is specifically designed for efficiency on large arrays of data. NumPy stores data in contiguous blocks of memory and uses C-based algorithms to perform complex computations on entire arrays—completely bypassing the need for slow Python for loops

1. The ndarray Object   
The core feature of NumPy is its N-dimensional array object, or ndarray. It is a fast, flexible container for large datasets that allows you to perform batch mathematical operations using the same syntax you would use for single scalar values. 
 Every array has two important attributes:  
 shape: A tuple indicating the size of each dimension.
 dtype: An object describing the data type of the array (e.g., float64, int32).

2. Creating Arrays
The easiest way to create an array is to use the np.array function, which accepts any sequence-like object (like a list) and converts it into a NumPy array.  

# Lecture 1: NumPy Basics, Creating Arrays, Arithmetic, and Data Types

In [73]:
import numpy as np 

# Creating a 1-dimensional array from a list
data1 = [6,2.7,5,8,8.8]
arr1 = np.array(data1)

# Creating a 2-dimensional array from a list of lists
data2 = [[2.7 ,3,9] , 
         [6,7,8]
         ]
arr2 = np.array(data2)
type(arr2)

# Creating a 2-dimensional  unequal element array  from a list of lists
arr3 = np.array([[3,4] , [4,5,6] ], dtype = object)
type(arr3)
print(arr3)
print(arr2)



[list([3, 4]) list([4, 5, 6])]
[[2.7 3.  9. ]
 [6.  7.  8. ]]


NumPy also provides built-in functions to generate arrays from scratch:  

In [74]:
np.zeros(10)   # Creates an array of 10 zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [75]:
np.ones((3,6))   # Creates a 3x6 multidimensional array of 1s
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [76]:
np.arange(5,15)  #  Works just like Python's built-in range() function, but returns an array instead of a list.

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

3. Array Arithmetic (Vectorization)
One of the most powerful features of arrays is that they enable you to perform operations on entire datasets without writing loops. NumPy users call this vectorization.  
Any arithmetic operations between equal-size arrays apply the operation element-by-element:  

In [77]:
arr  = np.array([[2,3,4] , 
                 [5,6,7]])

# Multiplication multiplies corresponding elements
print(arr*arr)

# Arithmetic with scalars propagates the value to each element
arr* 10 

[[ 4  9 16]
 [25 36 49]]


array([[20, 30, 40],
       [50, 60, 70]])

4. Data Types and Casting
You can explicitly convert (or cast) an array from one data type to another using the astype method.

In [78]:
arr = np.array([1, 2, 3, 4, 5]) # This is an integer array
float_arr = arr.astype(np.float64) # Now it is a float array

 ## Lecture 2: Indexing and Slicing (Learning how to select specific data, including basic slicing, boolean indexing, and "fancy" indexing).

Now that you know how to create arrays, you need to know how to extract specific data from them. NumPy offers several ways to index data, and some of them are quite different from standard Python lists.

1. Basic Indexing and Slicing (and "Views")

One-dimensional NumPy arrays act similarly to standard Python lists. You can select single elements or slice them using the start:stop:step syntax.

In [79]:
arr = np.arange(10)
print(arr)       # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(arr[5])    # Output: 5
print(arr[5:9])  # Output: array([5, 6, 7, 8])

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7 8]


Crucial Concept: Slices are VIEWS

Unlike Python lists, NumPy array slices are views of the original array, not copies. This means if you modify a slice, you modify the original array! This is done to save memory when working with massive datasets.

In [80]:
arr[5:8] = 12   # This "broadcasts" 12 to all three positions
print(arr)
# Output: [ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9]

""" If you ever actually want a copy, you must explicitly use """
copied_arr = arr[5:8].copy()
print(copied_arr)   # Output: [12 12 12]



[ 0  1  2  3  4 12 12 12  8  9]
[12 12 12]


For 2D arrays (matrices), elements at each index are no longer scalars, but 1D arrays. You can access individual elements by passing a comma-separated list of indices:

In [81]:
arr2d = np.array([[1,2,3] , 
                  [4,5,6] , 
                  [7,8,9]])
# Access row 0, column 2
print(arr2d[0,2])    # Output: 3
print(arr2d[1,1])    # Output: 5
print(arr2d[0,0])    # Output: 1

"""Access rows"""
print(arr2d[0])      # Output: [1 2 3]
print(arr2d[:, 1])   # Access an entire column = [2 5 8]
print(arr2d[:2])     # Access the first two rows
 


3
5
1
[1 2 3]
[2 5 8]
[[1 2 3]
 [4 5 6]]


In [82]:
# Access the first two columns
print(arr2d[:,:2])

[[1 2]
 [4 5]
 [7 8]]


In [83]:
# Access a subarray
print(arr2d[1:,1:])

[[5 6]
 [8 9]]


In [84]:
# Access the last row
print(arr2d[2])
print(arr2d[-1])

[7 8 9]
[7 8 9]


## 2. Boolean Indexing

This is an incredibly powerful feature for data cleaning. You can use arrays of boolean values (True / False) to filter your data.

Imagine you have an array of names and a matrix of data corresponding to those names:

In [ ]:
names = np.array(["Yashraj" , "Shahid" , "Yashraj" , "Yash" , "Pramveer"])
data = np.random.randn(5,5)   # A 5x4 matrix of random numbers
print(data)
name_yashraj = (names == "Yashraj")
print(name_yashraj)
data[:,name_yashraj]  # Use that boolean array to select the corresponding rows in 'data

[[-1.76636437 -0.10398828  0.79929282  0.02859447  0.47484878]
 [ 0.54636882  0.45848887  0.68906963  0.24510856 -1.23205916]
 [-0.18473529  2.1653278   1.11614173  2.25340733  0.32216492]
 [-0.48752103 -0.2737774  -0.32058123  0.15437314 -0.37324407]
 [-0.22620406 -0.11103276 -1.21084999  1.20856372 -0.47521987]]
[ True False  True False False]


array([[-1.76636437,  0.79929282],
       [ 0.54636882,  0.68906963],
       [-0.18473529,  1.11614173],
       [-0.48752103, -0.32058123],
       [-0.22620406, -1.21084999]])

### Boolean Indexing (Examples):

In [94]:
arr = np.array([10, 20, 30, 40, 50, 60])
"""Select values greater than 30"""
print(arr>30)
print(arr[arr>30])

[False False False  True  True  True]
[40 50 60]


In [95]:
# Select values less than 40
print(arr[arr<40])

[10 20 30]


### Boolean Indexing with 2D Arrays

In [104]:
arr3d = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

In [105]:
# Get all even numbers
print(arr3d[arr3d % 2 == 0 ])

[10 20 30 40 50 60 70 80 90]


In [107]:
 # Values greater than 20 AND less than 50:
print(arr3d[(arr3d>20) & (arr3d<50)])

[30 40]


 ### Modifying Values with Boolean Indexing

In [109]:
array = np.array([10,20,30,40,50,60])
array[array>30] = 60
print(array)

[10 20 30 60 60 60]


## 3. Fancy Indexing

In [118]:
np.empty((8,4))
for i in range(8):
    arr[i]  = i 

print(arr.astype(int))

# Select rows 4, 3, 0, and 6 in that exact order
arr[[4,3,0,6]]


[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

### Examples:
 

In [ ]:
# Basic 1D Fancy Indexing
np_arr = np.array([10,
                   20,
                   30,
                   40,
                   50,
                   60])
print(np_arr.shape)
print(np_arr[[3,3,4,5]])  # you are also controlling the order & can repeatc the elements 

(6,)
[40 40 50 60]


In [127]:
# Fancy Indexing in 2D Arrays:
np_arr2d = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])


In [ ]:
print(np_arr2d[2,1])
print(np_arr2d[[1,2]])   # Select specific rows

80
[[40 50 60]
 [70 80 90]]


In [ ]:
# Selecting specific elements (row-wise pairs)
print(np_arr2d[[0,1,2], [0,1,2]])  # diagonal matrix 

[10 50 80]


In [ ]:
# Important rule
# Fancy indexing returns a copy, not a view.
sub = np_arr2d[[0, 1]]
print(sub)
sub[0] = 100
print(sub)




[[10 20 30]
 [40 50 60]]
[[100 100 100]
 [ 40  50  60]]


 ## Lecture 3: 

Transposing Arrays and Universal Functions (Swapping axes and applying fast, element-wise array functions like square roots or exponentials).

Welcome to Lecture 3! Now that you know how to create and slice arrays, we are going to look at two powerful ways to manipulate and perform calculations on them: Transposing and Universal Functions.

### 1. Transposing Arrays and Swapping Axes

Transposing is a special form of reshaping that swaps the axes of an array. Just like slicing, transposing returns a view on the underlying data without actually copying anything in memory.

The simplest way to transpose a 2D array (a matrix) is using the .T attribute. This is extremely useful in mathematical and statistical modeling, such as calculating an inner matrix product using np.dot.

In [ ]:
# # Create a 3x5 matrix
arr = np.arange(15).reshape(3,5)
print(arr)
# Transpose it to a 5x3 matrix using .T
transposed = arr.T
print(transposed)   # shape (5,3)




[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


### Examples :

In [145]:
#  Basic 2D Matrix Transpose :
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])

print(a.T)


[[1 4]
 [2 5]
 [3 6]]


In [149]:
# 3D Array Transpose (Axis Swapping):
a = np.arange(24).reshape(2,3,4)
print(a)
print(a.shape)
print(a.T)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]


In [152]:
 # Custom Axis Rearrangement (np.transpose)
a = np.arange(24).reshape(2,3,4)
b = np.transpose(a , (1,0,2))
print(b)

[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]


| New axis position | Comes from old axis |
| ----------------- | ------------------- |
| axis 0            | axis 1              |
| axis 1            | axis 0              |
| axis 2            | axis 2              |

old : (2, 3, 4)
becomes : (3, 2, 4)


 ### Binary ufuncs (take two arrays and return one)

These functions take two arrays and perform an element-wise operation between them, returning a single new array.

In [ ]:
x = np.array([1,5,3])
y = np.array([2,2,8])
# Element-wise maximum: compares elements in x and y at the same index 
# and returns the larger one
np.maximum(x,y)   # Output: [2, 5, 8]


array([2, 5, 8])

#### Examples:

In [ ]:
print(np.add(x,y))
print(np.subtract(x,y))
print(np.multiply(x,y))
print(np.divide(x,y).astype(int))
print(np.power(x,y)) # Raises elements in first array to powers indicated in second array

[ 3  7 11]
[-1  3 -5]
[ 2 10 24]
[0 2 0]
[   1   25 6561]


### 2. Universal Functions (ufuncs)

A universal function, or ufunc, is a function that performs element-wise operations on data inside ndarray objects. You can think of them as fast, vectorized wrappers for simple mathematical functions. Because they are written in C, they are incredibly fast compared to standard Python loops.

Unary ufuncs (operate on a single array)

These functions take a single array and perform an operation on every single element.

In [ ]:
arr = np.array([1, 4, 9, 16, 25])

# Calculate the square root of every element
print(np.sqrt(arr))
# Output: [1. 2. 3. 4. 5.]

# Calculate the exponential (e^x) of every element
print(np.exp(arr))

Lecture 4: Array-Oriented Programming (Expressing conditional logic as array operations, mathematical/statistical methods, and sorting).

Lecture 5: File Input/Output and Linear Algebra (Saving/loading arrays to disk and basic matrix operations like dot products).

Lecture 6: Pseudorandom Number Generation & A Practical Example (Generating random data and building a "Random Walk" simulation).